# Generated by Django 3.0.2 on 2020-03-31 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='order',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Product', verbose_name='Продукт'),
        ),
    ]
